### ISSUE TITLE
Crash caused by NativeLoginStrategy

### ISSUE THREAD

**Issue by ilia-potylitsyn** [yandexmobile/yandex-login-sdk-android#14]
## Контекст
С 28 января в крашлитикс стали прилетать краши ` NativeLoginStrategy$ResultExtractor.tryExtractToken`
Краши задевают от 8 (минимально поддерживаемая нами) до 12 версии андроида. 13 андроида краш не коснулся
Версия login-sdk 2.5.1. Приложение с этой версией sdk появилось в маркете 20 января
### Android 8-11
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=312, result=-1, data=Intent { (has extras) }} to activity {ru.aviasales/com.yandex.authsdk.internal.AuthSdkActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: svi
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```
```
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: svi
       at android.os.Parcel.readParcelableCreator(Parcel.java:3107)
       at android.os.Parcel.readParcelable(Parcel.java:3029)
       at android.os.Parcel.readValue(Parcel.java:2931)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3318)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.BaseBundle.getString(BaseBundle.java:1164)
       at android.content.Intent.getStringExtra(Intent.java:8186)
       at com.yandex.authsdk.internal.strategy.NativeLoginStrategy$ResultExtractor.tryExtractToken(NativeLoginStrategy.java:86)
       at com.yandex.authsdk.internal.AuthSdkActivity.onActivityResult(AuthSdkActivity.java:86)
       at android.app.Activity.dispatchActivityResult(Activity.java:8541)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```
### Android 12
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=312, result=-1, data=Intent { (has extras) }} to activity {ru.aviasales/com.yandex.authsdk.internal.AuthSdkActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.yandex.passport.internal.account.h
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5946)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.yandex.passport.internal.account.h
       at android.os.Parcel.readParcelableCreator(Parcel.java:3429)
       at android.os.Parcel.readParcelable(Parcel.java:3337)
       at android.os.Parcel.readValue(Parcel.java:3239)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3636)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.BaseBundle.getString(BaseBundle.java:1196)
       at android.content.Intent.getStringExtra(Intent.java:9159)
       at com.yandex.authsdk.internal.strategy.NativeLoginStrategy$ResultExtractor.tryExtractToken(NativeLoginStrategy.java:86)
       at com.yandex.authsdk.internal.AuthSdkActivity.onActivityResult(AuthSdkActivity.java:86)
       at android.app.Activity.dispatchActivityResult(Activity.java:8659)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by java.lang.ClassNotFoundException: com.yandex.passport.internal.account.h
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:454)
       at android.os.Parcel.readParcelableCreator(Parcel.java:3403)
       at android.os.Parcel.readParcelable(Parcel.java:3337)
       at android.os.Parcel.readValue(Parcel.java:3239)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3636)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.BaseBundle.getString(BaseBundle.java:1196)
       at android.content.Intent.getStringExtra(Intent.java:9159)
       at com.yandex.authsdk.internal.strategy.NativeLoginStrategy$ResultExtractor.tryExtractToken(NativeLoginStrategy.java:86)
       at com.yandex.authsdk.internal.AuthSdkActivity.onActivityResult(AuthSdkActivity.java:86)
       at android.app.Activity.dispatchActivityResult(Activity.java:8659)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by java.lang.ClassNotFoundException: com.yandex.passport.internal.account.h
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:454)
       at android.os.Parcel.readParcelableCreator(Parcel.java:3403)
       at android.os.Parcel.readParcelable(Parcel.java:3337)
       at android.os.Parcel.readValue(Parcel.java:3239)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3636)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.BaseBundle.getString(BaseBundle.java:1196)
       at android.content.Intent.getStringExtra(Intent.java:9159)
       at com.yandex.authsdk.internal.strategy.NativeLoginStrategy$ResultExtractor.tryExtractToken(NativeLoginStrategy.java:86)
       at com.yandex.authsdk.internal.AuthSdkActivity.onActivityResult(AuthSdkActivity.java:86)
       at android.app.Activity.dispatchActivityResult(Activity.java:8659)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
## Воспроизведение
Самому краш воспроизвести не удалось, но за последнюю неделю он успел задеть больше трёхсот пользователей
По стектрейсу видно, что исключение прилетает в методе `onActivityResult` у `AuthSdkActivity` при попытке прочитать токен из Intent. Возможно проблема в обфускации: `com.yandex.passport.internal.account.h`

**Comment by sbrednikhin** [comment]
Есть аналогичная проблема.

**Comment by balmerdx** [comment]
Да, у нас так-же падает.

**Comment by AIGRIND-LLC** [comment]
Та же проблема. Выбилась в ТОП падений.
